name: Jekyll CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        bundle install
        npm install

    - name: Debug node_modules
      run: ls -R node_modules/bootstrap/scss

    - name: Build site
      run: bundle exec jekyll build --baseurl "/petteriheino.github.io"